config/routes.rb
Rails.application.routes.draw do


  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  root to: 'public/rakuten_games#index'

  namespace :admin do
    resources :users,only: [:index,:show]
    resources :rakuten_games,only: [:index,:show,:create] do
      resources :reviews,only: [:show,:destroy] do
        resources :comments,only: [:destroy]
        member do
          delete :user_destroy
        end
      end
    end
  end

  scope module: :public do
    resources :users,only: [:show,:edit,:update]
    resources :rakuten_games,only: [:show,:create] do
      resources :reviews,only: [:create,:index,:show,:update,:edit,:destroy] do
        resources :comments, only: [:destroy,:create]

      end
      collection do
        get :search
        post :review
      end
    end

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!
  def show
    @rakuten_game = RakutenGame.find(params[:rakuten_game_id])
    @review=Review.find(params[:id])
    @comments=@review.comments.all
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_rakuten_game_path(@review.rakuten_game_id)
  end

  def user_destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_user_path(@review.user_id)
  end

end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/show.html.erb
<p class="h4 bg-info pl-5">コメント一覧</p>
<div class="container mt-2">
  <div class="col-10 mx-auto">
    <table class="table">
      <tr class="bg-light">
        <td class="col-2">
          <%=image_tag @review.user.get_image(100,100) %>
        </td>
        <td class="col-8">
          <div class="row">
            <p class="bg-secondary text-white">投稿者</p>　<%=@review.user.name %> さん
          </div>
          <div class="row">
            <p class="bg-secondary text-white">評価</p>　<%=@review.score %>/5点
          </div>
          <p class="font-weight-bold"><%=@review.title %></p>
          <p><%=@review.review %></p>
          <%=link_to "レビューに戻る",admin_rakuten_game_path(@rakuten_game.id) %>
        </td>
      </tr>
    </table>

    <div class="mt-5">
      <table class="table">
        <tbody>
          <% if @comments.present? %>
            <% @comments.each do |comment| %>
              <tr>
                <td class="col-2">
                  <%=image_tag comment.user.get_image(100,100) %>
                </td>
                <td class="col-8">
                  <div class="row">
                    <p class="bg-secondary text-white">投稿者</p>
                    <p><%=comment.user.name %> さん</p>

                  </div>

                  <p><%=comment.comment %></p>
                </td>
                <td class="col-2">
                  <%=link_to "消去する",admin_rakuten_game_review_comment_path(@rakuten_game,comment.review_id,comment.id),method: :delete,"data-confirm"=>"本当に削除しますか？",class: "btn btn-danger" %>
                </td>
              </tr>
            <%end%>

          <%else%>
            <div class="h5 text-center mt-5">
              まだコメントが投稿されていません
            </div>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>