config/routes.rb
Rails.application.routes.draw do


  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  root to: 'public/rakuten_games#index'

  namespace :admin do
    resources :users,only: [:index,:show]
    resources :rakuten_games,only: [:index,:show,:create] do
      resources :reviews,only: [:show,:destroy] do
        resources :comments,only: [:destroy]
        member do
          delete :user_destroy
        end
      end
    end
  end

  scope module: :public do
    resources :users,only: [:show,:edit,:update]
    resources :rakuten_games,only: [:show,:create] do
      resources :reviews,only: [:create,:index,:show,:update,:edit,:destroy] do
        resources :comments, only: [:destroy,:create]

      end
      collection do
        get :search
        post :review
      end
    end

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rakuten_game.rb
class RakutenGame < ApplicationRecord
  has_many :reviews, dependent: :destroy

  
end

app/controllers/admin/rakuten_games_controller.rb
class Admin::RakutenGamesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @game = RakutenGame.page(params[:page]).order(created_at: :desc).per(20)
  end

  def show
    @rakuten_game = RakutenGame.find(params[:id])
    @review=@rakuten_game.reviews.page(params[:page]).order(created_at: :desc).per(20)
  end

  def create
    @game = RakutenGame.new(game_params)
    @game_title = RakutenGame.find_by(title: @game.title)

    if @game_title.present?
      redirect_to admin_rakuten_game_path(@game_title.id)
    else
      @game.save
      redirect_to admin_rakuten_game_path(@game.id)
    end
  end

  private

  def game_params
    params.require(:rakuten_game).permit(:title,:hardware,:smallimage_url,:largeimage_url,:item_url)
  end
end

app/helpers/admin/rakuten_games_helper.rb
module Admin::RakutenGamesHelper
end

app/views/admin/rakuten_games/index.html.erb
<p class="h4 bg-info pl-5">ゲーム一覧</p>
<div class="container mt-2">
  <table class="table">
    <tbody>
      <% @game.each do |game| %>
        <tr>
          <td class="col-2">
            <%=link_to (image_tag(game.smallimage_url)), game.item_url %>

          </td>
          <td>
            <%=link_to admin_rakuten_game_path(game.id) do %>
              <%=game.title %>
            <%end%>
            <p class="mt-2"><%=game.reviews.count %>件のレビュー</p>
          </td>
          <td><%=game.hardware %></td>
        </tr>

      <% end %>
    </tbody>

  </table>
  <div class="row">
    <div class="col-md-2 mt-2 mb-2 mx-auto">
      <%= paginate @game,window: 1,outer_window: 1 %>
    </div>
  </div>
</div>

app/views/admin/rakuten_games/show.html.erb
<div class="container mt-2">
  <div class="col-md-10 mx-auto">
    <div class="border bg-light py-5">
      <div class="row">
        <div class="col-md-4 mx-auto mt-3">
          <%=link_to (image_tag(@rakuten_game.largeimage_url)), @rakuten_game.item_url %>
        </div>
        <div class="col-md-7">
          <p class="font-weight-bold h3"><%=@rakuten_game.title %></p>
          <div class="row mt-5">
            <p class=" col-2 h5">機種</p>
            <div class="col-5 font-weight-bold h5"><%=@rakuten_game.hardware %></div>
          </div>
          <div class="row mt-3">
            <p class="h5 col-3">平均点</p>
            <div class="col-3 h5">
              <%=@rakuten_game.reviews.average(:score) %>/5点
            </div>
          </div>
          <div class="row mt-3">
            <p class="h5 col-3">レビュー数</p>
            <div class="col-3 h5">
              <%=@rakuten_game.reviews.count %>件
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-10 mx-auto">

    <p class="h4 bg-success text-white col-3 text-center mt-3">レビュー一覧</p>
    <table class="table">
      <tbody>
        <% if @review.present? %>
          <% @review.each do |review| %>
            <tr>
              <td class="col-2">
                <%=image_tag review.user.get_image(100,100) %>
              </td>
              <td class="col-8">
                <div class="row">
                  <p class="bg-secondary text-white">投稿者</p>　<%=review.user.name %> さん
                </div>
                <div class="row">
                  <p class="bg-secondary text-white">評価</p>　<%=review.score %>/5点
                </div>
                <p class="font-weight-bold">
                  <%=link_to admin_rakuten_game_review_path(@rakuten_game,review.id) do %>
                    <%=review.title %>
                  <%end%>
                </p>
                <p><%=review.review %></p>
                <%=link_to admin_rakuten_game_review_path(@rakuten_game,review.id) do %>
                  <%=review.comments.count %>件のコメント
                <%end%>

              </td>
              <td class="col-2">
                <%=link_to "削除する",admin_rakuten_game_review_path(@rakuten_game,review), method: :delete,"data-confirm"=>"本当に削除しますか？",class: "btn btn-danger btn-sm mt-2" %>
              </td>
            </tr>
          <%end%>
        <%else%>
          <div class="h5 text-center mt-5">
            まだレビューが投稿されていません
          </div>
        <%end%>
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="col-md-2 mt-2 mb-2 mx-auto">
      <%= paginate @review,window: 1,outer_window: 1 %>
    </div>
  </div>
</div>