config/routes.rb
Rails.application.routes.draw do


  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  root to: 'public/rakuten_games#index'

  namespace :admin do
    resources :users,only: [:index,:show]
    resources :rakuten_games,only: [:index,:show,:create] do
      resources :reviews,only: [:show,:destroy] do
        resources :comments,only: [:destroy]
        member do
          delete :user_destroy
        end
      end
    end
  end

  scope module: :public do
    resources :users,only: [:show,:edit,:update]
    resources :rakuten_games,only: [:show,:create] do
      resources :reviews,only: [:create,:index,:show,:update,:edit,:destroy] do
        resources :comments, only: [:destroy,:create]

      end
      collection do
        get :search
        post :review
      end
    end

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  has_many :reviews, dependent: :destroy
  has_many :comments,dependent: :destroy



  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    @review = @user.reviews
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<p class="h4 bg-info pl-5">会員一覧</p>
<div class="container mt-2">
  <table class="table">
    <tbody>
      <% @user.each do |user| %>
        <tr>
          <td class="col-2">
            <%=image_tag user.get_image(100,100) %>

          </td>
          <td>
            <%=link_to admin_user_path(user.id) do %>
              <%=user.name %>
            <%end%>
            <p class="mt-2"><%=user.reviews.count %>件のレビュー</p>
          </td>

        </tr>
      <% end %>
    </tbody>
    
  </table>
</div>

app/views/admin/users/show.html.erb
<p class="h4 bg-info pl-5"><%=@user.name %>さんのレビュー一覧</p>
<div class="container">
  <div class="col-md-10 mx-auto">
    <div class="border bg-light py-5">
      <div class="row">
        <div class="col-md-4 mx-auto mt-3">
          <%=image_tag @user.get_image(200,200) %>
        </div>
        <div class="col-md-7">
          <div class="row">
            <p class="col-4">ニックネーム</p>
            <p class="font-weight-bold h4 col-8">
              <%=@user.name %>
            </p>
          </div>
          <div class="row mt-3">
            <p class="col-4">レビューした数</p>
            <p class="col-3 font-weight-bold h5"><%=@user.reviews.count %>件</p>
          </div>
        </div>
      </div>
    </div>
　　<p class="h4 bg-success text-white col-3 text-center mt-3">レビュー</p>
    <table class="table">
      <tbody>
        <% @review.each do |review| %>
          <tr>
            <td class="col-2">
              <%=link_to (image_tag(review.rakuten_game.smallimage_url)), review.rakuten_game.item_url %>
            </td>
            <td class="col-8">
              <div class="row">
                <p class="bg-secondary text-white">評価</p>　<%=review.score %>/5点
              </div>
              <p class="font-weight-bold"><%=review.title %></p>
              <p><%=review.review %></p>

            </td>
            <td class="col-2">
              <%=link_to "削除する",user_destroy_admin_rakuten_game_review_path(review.rakuten_game_id,review), method: :delete,"data-confirm"=>"本当に削除しますか？",class: "btn btn-danger btn-sm mt-2" %>
            </td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>