config/routes.rb
Rails.application.routes.draw do


  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }


  root to: 'public/rakuten_games#index'

  namespace :admin do
    resources :users,only: [:index,:show]
    resources :rakuten_games,only: [:index,:show,:create] do
      resources :reviews,only: [:show,:destroy] do
        resources :comments,only: [:destroy]
        member do
          delete :user_destroy
        end
      end
    end
  end

  scope module: :public do
    resources :users,only: [:show,:edit,:update]
    resources :rakuten_games,only: [:show,:create] do
      resources :reviews,only: [:create,:index,:show,:update,:edit,:destroy] do
        resources :comments, only: [:destroy,:create]

      end
      collection do
        get :search
        post :review
      end
    end

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  
  validates :comment,presence: true
end

app/models/rakuten_game.rb
class RakutenGame < ApplicationRecord
  has_many :reviews, dependent: :destroy

  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :rakuten_game
  has_many :comments,dependent: :destroy

  validates :score,presence: true
  validates :title,presence: true
  validates :review,presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  has_many :reviews, dependent: :destroy
  has_many :comments,dependent: :destroy



  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  def destroy
    @review=Review.find(params[:review_id])
    @comment=Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_rakuten_game_review_path(@review.rakuten_game_id,@review.id)
  end
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/rakuten_games_controller.rb
class Admin::RakutenGamesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @game = RakutenGame.page(params[:page]).order(created_at: :desc).per(20)
  end

  def show
    @rakuten_game = RakutenGame.find(params[:id])
    @review=@rakuten_game.reviews.page(params[:page]).order(created_at: :desc).per(20)
  end

  def create
    @game = RakutenGame.new(game_params)
    @game_title = RakutenGame.find_by(title: @game.title)

    if @game_title.present?
      redirect_to admin_rakuten_game_path(@game_title.id)
    else
      @game.save
      redirect_to admin_rakuten_game_path(@game.id)
    end
  end

  private

  def game_params
    params.require(:rakuten_game).permit(:title,:hardware,:smallimage_url,:largeimage_url,:item_url)
  end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!
  def show
    @rakuten_game = RakutenGame.find(params[:rakuten_game_id])
    @review=Review.find(params[:id])
    @comments=@review.comments.all
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_rakuten_game_path(@review.rakuten_game_id)
  end

  def user_destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_user_path(@review.user_id)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    @review = @user.reviews
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    case resource
    when User
      user_path(current_user.id)
    when Admin
      admin_rakuten_games_path

    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/rakuten_games_helper.rb
module Admin::RakutenGamesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">

          <a class="navbar-brand p-3">
            <%=link_to root_path do %>
              <%=image_tag 'logo.jpg', size: '200x80' %>
            <%end%>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>



              <li class="nav-item">
                <%=link_to "マイページ", user_path(current_user.id),class: 'mr-3 btn btn-outline-secondary nav-link text-dark' %>
              </li>

              <li class="nav-item">
                <%=link_to "検索", search_rakuten_games_path,class: 'mr-3 btn btn-outline-secondary nav-link text-dark' %>
              </li>

              <li class="nav-item">
                <%=link_to "ログアウト", destroy_user_session_path,method: :delete, class: 'mr-3 btn btn-outline-secondary nav-link text-dark' %>
              </li>
            <%elsif admin_signed_in? %>
              <li class="nav-item">
                <%=link_to "検索", search_rakuten_games_path,class: 'mr-3 btn btn-outline-secondary nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%=link_to "ゲーム一覧", admin_rakuten_games_path,class: 'mr-3 btn btn-outline-secondary nav-link text-dark' %>
              </li>

              <li class="nav-item">
                <%=link_to "ユーザ一覧", admin_users_path,class: 'mr-3 btn btn-outline-secondary nav-link text-dark' %>
              </li>

              <li class="nav-item">
                <%=link_to "ログアウト", destroy_admin_session_path,method: :delete, class: 'mr-3 btn btn-outline-secondary nav-link text-dark' %>
              </li>

            <% else %>

              <li class="nav-item">
                <%=link_to "検索", search_rakuten_games_path,class: 'mr-3 btn btn-outline-secondary nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark mr-3 btn btn-outline-secondary' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark mr-3 btn btn-outline-secondary' %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>
    <footer>
      <div class="bg-info pt-2 mt-4"></div>
      <div class="text-center mt-4 mb-4">
        <a href="https://webservice.rakuten.co.jp/" target="_blank"><img src="https://webservice.rakuten.co.jp/img/credit/200709/credit_31130.gif" border="0" alt="Rakuten Web Service Center" title="Rakuten Web Service Center" width="311" height="30"/></a>
      </div>
      <div class="text-center mb-3">Logo generated by <a href="https://www.designevo.com/" title="Free Online Logo Maker">DesignEvo free logo designer</a></div>
    </footer>
  </body>
</html>